//This file is generated by atlas-plugins, 
//the [autogenerated] block will be replaced when gradle runs, 
//the remainder of the file can be edited as you like, 
//as long as the [autogenerated] and [/autogenerated] commentaries aren't removed.

//[autogenerated]
unroll {defaultPattern '#featureName[#iterationIndex]'}
//[/autogenerated]
